require("mason").setup()

require("mason-tool-installer").setup({
  ensure_installed = {
    "lua-language-server",
    "stylua",
    "vtsls",
    "vue-language-server",
    "svelte-language-server",
    "tailwindcss-language-server",
    "oxfmt",
    "oxlint",
    "gopls",
    "goimports",
    "golangci-lint",
    "rust-analyzer",
    "zls",
    "ols",
    "pyright",
    "intelephense",
    "php-cs-fixer",
    "blade-formatter",
    "clangd",
    "bash-language-server",
    "shfmt",
    "prisma-language-server",
    "dockerfile-language-server",
    "docker-compose-language-service",
    "json-lsp",
    "sqlfluff",
  },
  auto_update = false,
  run_on_start = true,
  start_delay = 3000,
  debounce_hours = 24,
  integrations = {
    ["mason-lspconfig"] = false,
    ["mason-null-ls"] = false,
    ["mason-nvim-dap"] = false,
  },
})
